-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT line.ID AS ENTITY_ID, line.NAME AS ENTITY_NAME,
       line.REGION, line.CATEGORY, line.STATUS,
       COUNT(*) AS EVENT_COUNT, SUM(observation.UPSET_COUNT) AS UPSET_COUNT,
       SUM(observation.OPERATING_HOURS) AS OPERATING_HOURS,
       SUM(observation.PLANNED_HOURS) AS PLANNED_HOURS,
       SUM(observation.DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(observation.PM_DUE) AS PM_DUE, SUM(observation.PM_COMPLETED) AS PM_COMPLETED,
       SUM(observation.ORE_FEED_T) AS ORE_FEED_T,
       SUM(observation.NI_RECOVERED_T) AS NI_RECOVERED_T, SUM(observation.NI_FEED_T) AS NI_FEED_T,
       SUM(observation.ENERGY_MWH) AS ENERGY_MWH,
       100.0 * SUM(observation.NI_RECOVERED_T) / NULLIF(SUM(observation.NI_FEED_T), 0) AS NI_RECOVERY_PCT,
       SUM(observation.ENERGY_MWH) / NULLIF(SUM(observation.ORE_FEED_T), 0) AS ENERGY_MWH_PER_T,
       100.0 * SUM(observation.OPERATING_HOURS) / NULLIF(SUM(observation.PLANNED_HOURS), 0) AS LINE_AVAILABILITY_PCT,
       100.0 * SUM(observation.PM_COMPLETED) / NULLIF(SUM(observation.PM_DUE), 0) AS PM_COMPLIANCE_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.LINE_DAILY observation
JOIN RAW.LINES line ON line.ID = observation.ENTITY_ID
GROUP BY line.ID, line.NAME, line.REGION, line.CATEGORY, line.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(NI_RECOVERED_T) AS NI_RECOVERED_T, SUM(NI_FEED_T) AS NI_FEED_T,
       SUM(ORE_FEED_T) AS ORE_FEED_T, SUM(ENERGY_MWH) AS ENERGY_MWH,
       SUM(UPSET_COUNT) AS UPSET_COUNT,
       100.0 * SUM(NI_RECOVERED_T) / NULLIF(SUM(NI_FEED_T), 0) AS NI_RECOVERY_PCT
FROM RAW.LINE_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.UPSET_CAUSES
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT ROOT_CAUSE, SUM(UPSET_COUNT) AS UPSET_COUNT,
       SUM(DOWNTIME_HOURS) AS DOWNTIME_HOURS,
       SUM(NI_FEED_T) - SUM(NI_RECOVERED_T) AS NI_LOST_T
FROM RAW.LINE_DAILY
WHERE UPSET_COUNT > 0
GROUP BY ROOT_CAUSE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(NI_RECOVERED_T) AS NI_RECOVERED_T, SUM(NI_FEED_T) AS NI_FEED_T,
         SUM(ORE_FEED_T) AS ORE_FEED_T, SUM(ENERGY_MWH) AS ENERGY_MWH,
         SUM(UPSET_COUNT) AS UPSETS,
         SUM(OPERATING_HOURS) AS OPERATING_HOURS, SUM(PLANNED_HOURS) AS PLANNED_HOURS,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.LINE_DAILY
), fleet AS (SELECT COUNT(*) AS LINE_COUNT FROM RAW.LINES),
spares AS (
  SELECT 100.0 * SUM(LEAST(ON_HAND_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT
  FROM RAW.CRITICAL_SPARES
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Nickel Recovery' AS TITLE,
         100.0 * NI_RECOVERED_T / NULLIF(NI_FEED_T, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Process Upsets', UPSETS, '' FROM observations
  UNION ALL SELECT 3, 'Energy Intensity', ENERGY_MWH / NULLIF(ORE_FEED_T, 0), ' MWh/t' FROM observations
  UNION ALL SELECT 4, 'Ore Processed (dry t)', ORE_FEED_T, '' FROM observations
  UNION ALL SELECT 5, 'Line Availability', 100.0 * OPERATING_HOURS / NULLIF(PLANNED_HOURS, 0), '%' FROM observations
  UNION ALL SELECT 6, 'Lines Monitored', LINE_COUNT, '' FROM fleet
  UNION ALL SELECT 7, 'Critical Spares Coverage', COVERAGE_PCT, '%' FROM spares
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.TITLE = 'Energy Intensity' THEN TRIM(TO_VARCHAR(metrics.VALUE_NUM, '990.000'))
                WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.UPSET_CAUSES SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
