-- Generated from generator/demo_specs/aws-indonesia-mining-nickel-processing.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-mining-nickel-processing
-- This is the schema that is actually deployed for ID_MINING_NICKEL_PROCESSING.

-- Alerts fire on the bottom tail of Recovery Rate
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_RECOVERY_RATE) AS T
  FROM RAW.PLANT_SENSORS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_RECOVERY_RATE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_RECOVERY_RATE), 2) AS AVG_RECOVERY_RATE,
  ROUND(AVG(f.KPI_KILNS_ACTIVE), 2) AS AVG_KILNS_ACTIVE,
  ROUND(AVG(f.KPI_SLAG_RATIO), 2) AS AVG_SLAG_RATIO,
  ROUND(AVG(f.KPI_SPECIFIC_ENERGY), 2) AS AVG_SPECIFIC_ENERGY,
  ROUND(AVG(f.KPI_ORE_GRADE_AVG), 2) AS AVG_ORE_GRADE
FROM RAW.PLANT_SENSORS f
JOIN RAW.PROCESS_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_RECOVERY_RATE), 2) AS AVG_RECOVERY_RATE,
  ROUND(AVG(f.KPI_KILNS_ACTIVE), 2) AS AVG_KILNS_ACTIVE,
  ROUND(AVG(f.KPI_SLAG_RATIO), 2) AS AVG_SLAG_RATIO,
  ROUND(AVG(f.KPI_SPECIFIC_ENERGY), 2) AS AVG_SPECIFIC_ENERGY,
  ROUND(AVG(f.KPI_ORE_GRADE_AVG), 2) AS AVG_ORE_GRADE
FROM RAW.PLANT_SENSORS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_RECOVERY_RATE) AS KPI_RECOVERY_RATE, AVG(KPI_KILNS_ACTIVE) AS KPI_KILNS_ACTIVE, AVG(KPI_ORE_GRADE_AVG) AS KPI_ORE_GRADE_AVG, AVG(KPI_SLAG_RATIO) AS KPI_SLAG_RATIO, AVG(KPI_SPECIFIC_ENERGY) AS KPI_SPECIFIC_ENERGY FROM RAW.PLANT_SENSORS),
     en AS (SELECT SUM(KPI_NPI_OUTPUT_MTD) AS KPI_NPI_OUTPUT_MTD, SUM(KPI_ENERGY_COST) AS KPI_ENERGY_COST FROM RAW.PROCESS_DOCS)
  SELECT 1 AS SORT_ORDER, 'NPI Output (MTD)' AS TITLE, KPI_NPI_OUTPUT_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_NPI_OUTPUT_MTD) / 1000)) AS DECIMAL(38,0))) || 'K' || ' ' || 'tonnes' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Recovery Rate' AS TITLE, KPI_RECOVERY_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RECOVERY_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Energy Cost' AS TITLE, KPI_ENERGY_COST AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_ENERGY_COST) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Kilns Active' AS TITLE, KPI_KILNS_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_KILNS_ACTIVE)) AS DECIMAL(38,0))) || '/28' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Ore Grade Avg' AS TITLE, KPI_ORE_GRADE_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ORE_GRADE_AVG), 1) AS DECIMAL(38,1))) || '% Ni' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Slag Ratio' AS TITLE, KPI_SLAG_RATIO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SLAG_RATIO)) AS DECIMAL(38,0))) || ':1' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Specific Energy' AS TITLE, KPI_SPECIFIC_ENERGY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SPECIFIC_ENERGY), 1) AS DECIMAL(38,1))) || ' ' || 'MWh/t' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
