-- Upset-risk scoring and nickel-recovery forecast over the synthetic snapshot.
-- Predicts P(process upset in the next 7 days) per line and reports
-- out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.UPSET_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, t.CATEGORY, t.AGE_YEARS,
       r.SETPOINT_DEV_PCT, r.SHELL_TEMP_C,
       AVG(r.SETPOINT_DEV_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS SETPOINT_DEV_7D,
       SUM(r.UPSET_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS UPSETS_30D,
       IFF(SUM(r.UPSET_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'UPSET', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.LINE_DAILY r JOIN RAW.LINES t ON t.ID = r.ENTITY_ID
-- Captive power trips are not line-driven, so they are excluded from training.
WHERE r.ROOT_CAUSE <> 'Captive power trip' OR r.UPSET_COUNT = 0;

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.UPSET_TRAIN AS
SELECT CATEGORY, AGE_YEARS, SETPOINT_DEV_PCT, SHELL_TEMP_C, SETPOINT_DEV_7D, UPSETS_30D, LABEL
FROM ML.UPSET_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.UPSET_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, AGE_YEARS, SETPOINT_DEV_PCT, SHELL_TEMP_C, SETPOINT_DEV_7D, UPSETS_30D, LABEL
FROM ML.UPSET_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.UPSET_RISK_MODEL(
  INPUT_DATA => TABLE(ML.UPSET_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.UPSET_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.UPSET_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'SETPOINT_DEV_PCT', SETPOINT_DEV_PCT,
           'SHELL_TEMP_C', SHELL_TEMP_C, 'SETPOINT_DEV_7D', SETPOINT_DEV_7D, 'UPSETS_30D', UPSETS_30D)):probability:UPSET::FLOAT AS P
  FROM ML.UPSET_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'UPSET', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'UPSET', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'UPSET', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'UPSET', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per line (label unknown, so excluded from features).
CREATE TABLE ML.UPSET_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.UPSET_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.UPSET_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'AGE_YEARS', AGE_YEARS, 'SETPOINT_DEV_PCT', SETPOINT_DEV_PCT,
           'SHELL_TEMP_C', SHELL_TEMP_C, 'SETPOINT_DEV_7D', SETPOINT_DEV_7D, 'UPSETS_30D', UPSETS_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:UPSET::FLOAT, 4) AS UPSET_PROB_7D,
       CASE WHEN P:probability:UPSET::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:UPSET::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Network-wide nickel-recovery forecast (14 days) from the daily series.
CREATE VIEW ML.DAILY_RECOVERY AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, 100.0 * SUM(NI_RECOVERED_T) / SUM(NI_FEED_T) AS NI_RECOVERY_PCT
FROM RAW.LINE_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.RECOVERY_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_RECOVERY),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'NI_RECOVERY_PCT'
);

CREATE TABLE ML.RECOVERY_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, LEAST(100, FORECAST) AS NI_RECOVERY_PCT,
       LOWER_BOUND, LEAST(100, UPPER_BOUND) AS UPPER_BOUND
FROM TABLE(ML.RECOVERY_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
