-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Nickel Processing Optimization
-- ============================================================================
USE DATABASE NICKEL_PROCESSING;
USE SCHEMA ML;

-- ML.FORECAST: RECOVERY_RATE_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.RECOVERY_RATE_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.RECOVERY_ANALYTICS'),
  SERIES_COLNAME => 'LINE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.RECOVERY_RATE_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.RECOVERY_RATE_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: PROCESS_DRIFT_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.PROCESS_DRIFT_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PROCESS_DRIFT'),
  SERIES_COLNAME => 'LINE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.PROCESS_DRIFT_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.PROCESS_DRIFT_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PROCESS_DRIFT'), SERIES_COLNAME => 'LINE_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

