-- ============================================================================
-- 99_RESET.SQL — Reset Nickel Processing Optimization to clean demo state
-- ============================================================================
USE DATABASE NICKEL_PROCESSING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_SENSORS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT_DRIFT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_RECOVERY SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PLANT_KPI_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.RECOVERY_ANALYTICS REFRESH;
ALTER DYNAMIC TABLE CURATED.ENERGY_EFFICIENCY REFRESH;
ALTER DYNAMIC TABLE CURATED.PROCESS_DRIFT REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM NICKEL_PROCESSING.RAW.PLANT_SENSORS → 1000000
-- SELECT COUNT(*) FROM NICKEL_PROCESSING.RAW.PRODUCTION_BATCHES → 50000
-- SELECT COUNT(*) FROM NICKEL_PROCESSING.RAW.ENERGY_CONSUMPTION → 200000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_RECOVERY RESUME;
ALTER TASK IF EXISTS APP.TASK_DETECT_DRIFT RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_SENSORS RESUME;
